# $Id$
# Legacy makefile for DJGPP
# No support for the Husky build environment.

CC=	gcc
CFLAGS= -Wall -s
CDEFS=	-D__FLAT__
COPT=	-O3 -fomit-frame-pointer -fstrength-reduce -mcpu=i486
LIB=	ar
RANLIB= ranlib
OBJ=	.o

TARGET= smapidjg.a

include makefile.inc


# Thunderbirds are go!

.c.o:
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<
	$(LIB) r $(TARGET) $@

all: $(TARGET)

$(TARGET): $(OBJS)
	$(RANLIB) $(TARGET)

clean:
	-DEL *.o

distclean: clean
	-DEL $(TARGET)
