# $Id$
# Microsoft Visual C++ Makefile for build static library

CC=     cl
CFLAGS= -nologo -Zp1
CDEFS=  -I.. -D__NT__ -D_CONSOLE
COPT=   -O2
TLIB=    lib -nologo
_EXE=	.exe
_OBJ=	.obj
_LIB=	.lib
LIBSUFFIX=mvc

include makefile.inc

.c$(_OBJ):
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<

all: $(TARGETLIB)

$(TARGETLIB): $(OBJS)
	$(TLIB) /out:$@ $(OBJS)


clean:
	-del *$(_OBJ)

distclean: clean
	-del $(TARGETLIB)
