# $Id$
# Legacy makefile for building on a generic Unix system
# No support for the Husky build environment

CC=	cc
LD=	ld
CFALGS=
CDEFS=	-DUNIX
COPT=
LIB=	ar
RANLIB=	ranlib

TARGET=	libsmapiunix.a
all: $(TARGET)

include makefile.inc


# Thunderbirds are go!

.c.o:
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<
	$(LIB) r $(TARGET) $@

$(TARGET): $(OBJS)
	$(RANLIB) $(TARGET)

clean:
	-rm *.o
	-rm $(TARGET)

distclean:
	-rm libsmapiunix.so
