# $Id$
# Microsoft Visual C++ Makefile for build static library

CC=     cl
CFLAGS= -nologo -Zp1
CDEFS=  -D__NT__ -DWIN32 -D_CONSOLE -DINTEL
COPT=   -O2
LIB=    lib -nologo

SMAPIL= smapimvc.lib

include makefile.inc


.c.obj:
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<

all: $(SMAPIL)

$(SMAPIL): $(OBJS)
	$(LIB) /out:$@ $(OBJS)

clean:
	-del *.obj

distclean: clean
	-del *.lib
