# Makefile for Building SMAPI with Borland C for DOS.
# No support for Husky build environment.

CC=	bcc
CFLAGS=	-w -ml
CDEFS=	-DMSDOS
COPT=	-O1
LIB=	tlib
ASM=	tasm
OBJ=	.obj

TARGET=	smapibcd.lib

include makefile.inc

# Thunderbirds are go!

.c.obj:
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<
	$(LIB) $(TARGET) -+$@

.asm.obj:
	$(ASM) -ml $<
	$(LIB) $(TARGET) -+$@

$(TARGET): $(OBJS)

clean:
	-DEL *.OBJ

distclean: clean
	-DEL SMAPIBCD.LIB
