# $Id$
#
# Common makefiles part (include-file)

OBJS=	1stchar.o  \
	api_sdm.o  \
	sq_area.o  \
	sq_hash.o  \
	sq_help.o  \
	sq_idx.o   \
	sq_kill.o  \
	sq_lock.o  \
	sq_misc.o  \
	sq_msg.o   \
	sq_read.o  \
	sq_uid.o   \
	sq_write.o \
	api_jam.o  \
	cvtdate.o  \
	date2bin.o \
	dosdate.o  \
	fexist.o   \
	ffind.o    \
	flush.o    \
	locking.o  \
	months.o   \
	msgapi.o   \
	parsenn.o  \
	patmat.o   \
	qksort.o   \
	strextra.o \
	strftim.o  \
	strocpy.o  \
	structrw.o \
	trail.o    \
	weekday.o  \
	setfsize.o \
	tdelay.o   \
	genmsgid.o
