CC=	bcc
CFLAGS=	-w
CDEFS=	-DOS2
COPT=	-O2
LIB=	tlib

TARGET=	smapibco.lib

OBJS=	1stchar.obj  \
	api_sdm.obj  \
	api_sq.obj   \
	cvtdate.obj  \
	date2bin.obj \
	dosdate.obj  \
	fexist.obj   \
	ffind.obj    \
	flush.obj    \
	months.obj   \
	msgapi.obj   \
	parsenn.obj  \
	qksort.obj   \
	strftim.obj  \
	strocpy.obj  \
	trail.obj    \
	weekday.obj

# Thunderbirds are go!

.c.obj:
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<
	$(LIB) $(TARGET) -+$@
    
$(TARGET): $(OBJS)
