# $Id$
# Makefile for High C for OS/2
# No support for the Husky build environment

CC=	hc
CFLAGS=	-w4 -Hmscerr -I..\smapi -I..\..\huskylib
CDEFS=	-DOS2
COPT=	-O3
LIB=	lib
OBJ=	.obj

TARGET=	smapihco.lib

include makefile.inc

# Thunderbirds are go!

.c.obj:
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<
	$(LIB) $(TARGET) -replace $@ -nobackup -nobanner

$(TARGET): $(OBJS)

clean:
	-DEL *.OBJ

distclean:
	-DEL $(TARGET)
