# Makefile for building a OS/2 SMAPI librarywith Borland C++ 2.0 for OS/2
# No support for the Husky build environment

CC=	bcc
CFLAGS=	-I..\smapi -I..\..\huskylib -w
CDEFS=	-DOS2
COPT=	-O2
LIB=	tlib
OBJ=	.obj

TARGET=	smapibco.lib

include makefile.inc

# Thunderbirds are go!

.c.obj:
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<
	$(LIB) $(TARGET) -+$@

$(TARGET): $(OBJS)

clean:
	-DEL *.obj

distclean: clean
	-DEL $(TARGET)

